version: '2'
services:
  central-ledger:
    image: ${API_IMAGE}:latest
    environment:
     CLEDG_DATABASE_URI: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/central_ledger_functional"
     CLEDG_ENABLE_BASIC_AUTH: "true"
     CLEDG_HOSTNAME: ${CLEDG_HOSTNAME}
     CLEDG_EXPIRES_TIMEOUT: ${CLEDG_EXPIRES_TIMEOUT}
  central-ledger-admin:
    image: ${ADMIN_IMAGE}:latest
    environment:
     CLEDG_DATABASE_URI: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/central_ledger_functional"
     CLEDG_ENABLE_BASIC_AUTH: "true"
