ALTER TABLE accounts ADD COLUMN "key" CHARACTER VARYING(148) NULL;
ALTER TABLE accounts ADD COLUMN "secret" CHARACTER VARYING(4000) NULL;

ALTER TABLE accounts ADD CONSTRAINT "UK_KEY" UNIQUE
  ("key");
