CREATE TABLE IF NOT EXISTS transfers (
  "transferUuid" UUID NOT NULL,
  "state" CHARACTER VARYING(10) NOT NULL,
  "ledger" CHARACTER VARYING(1024) NOT NULL,
  "debitAccount" CHARACTER VARYING(1024) NOT NULL,
  "debitAmount" DECIMAL(10,2) DEFAULT 0 NOT NULL,
  "debitMemo" CHARACTER VARYING(4000) NULL,
  "debitInvoice" CHARACTER VARYING(1024) NULL,
  "creditAccount" CHARACTER VARYING(1024) NOT NULL,
  "creditAmount" DECIMAL(10,2) DEFAULT 0 NOT NULL,
  "creditMemo" CHARACTER VARYING(4000) NULL,
  "creditInvoice" CHARACTER VARYING(1024) NULL,
  "executionCondition" CHARACTER VARYING(4000) NULL,
  "cancellationCondition" CHARACTER VARYING(4000) NULL,
  "rejectionReason" CHARACTER VARYING(10) NULL,
  "expiresAt" TIMESTAMP WITH TIME ZONE NULL,
  "additionalInfo" CHARACTER VARYING(4000) NULL,
  "preparedDate" TIMESTAMP WITH TIME ZONE NULL,
  "executedDate" TIMESTAMP WITH TIME ZONE NULL
);

CREATE INDEX "IDX_TRANSFER_UUID" ON transfers
  ("transferUuid" ASC);
ALTER TABLE transfers ADD CONSTRAINT "PK_TRANSFER_UUID" PRIMARY KEY
  ("transferUuid");
ALTER TABLE transfers ADD CONSTRAINT "UK_DEBIT_INVOICE" UNIQUE
  ("debitInvoice");
ALTER TABLE transfers ADD CONSTRAINT "UK_CREDIT_INVOICE" UNIQUE
  ("creditInvoice");
