ALTER TABLE "transfers" ADD COLUMN "debitInvoice" CHARACTER VARYING(1024) NULL;
ALTER TABLE "transfers" ADD COLUMN "creditInvoice" CHARACTER VARYING(1024) NULL;
ALTER TABLE "transfers" ADD CONSTRAINT "UK_DEBIT_INVOICE" UNIQUE
  ("debitInvoice");
ALTER TABLE "transfers" ADD CONSTRAINT "UK_CREDIT_INVOICE" UNIQUE
  ("creditInvoice");