CREATE TABLE IF NOT EXISTS accounts (
  "accountId" SERIAL NOT NULL,
  "name" CHARACTER VARYING(256) NOT NULL,
  "createdDate" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE INDEX "IDX_ACCOUNT_ID" ON accounts
  ("accountId" ASC);
ALTER TABLE accounts ADD CONSTRAINT "PK_ACCOUNT_ID" PRIMARY KEY
  ("accountId");
CREATE INDEX "IDX_ACCOUNT_NAME" ON accounts
  ("name" ASC);
ALTER TABLE accounts ADD CONSTRAINT "UK_ACCOUNT_NAME" UNIQUE
  ("name");
