ALTER TABLE "transfers" DROP CONSTRAINT "UK_DEBIT_INVOICE";
ALTER TABLE "transfers" DROP CONSTRAINT "UK_CREDIT_INVOICE";
ALTER TABLE "transfers" DROP COLUMN "debitInvoice" RESTRICT;
ALTER TABLE "transfers" DROP COLUMN "creditInvoice" RESTRICT;