ALTER TABLE transfers ADD COLUMN "creditRejected" SMALLINT DEFAULT 0 NOT NULL;
ALTER TABLE transfers ADD COLUMN "creditRejectionMessage" CHARACTER VARYING(4000) NULL;
ALTER TABLE transfers ADD COLUMN "rejectedDate" TIMESTAMP WITH TIME ZONE NULL;
