CREATE TABLE IF NOT EXISTS users (
  "userId" UUID NOT NULL,
  "key" CHARACTER VARYING (256) NOT NULL,
  "lastName" CHARACTER VARYING (128) NOT NULL,
  "firstName" CHARACTER VARYING (128) NOT NULL,
  "email" CHARACTER VARYING (256) NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdDate" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  CONSTRAINT users_pkey PRIMARY KEY ("userId"),
  CONSTRAINT "UK_USERS_KEY" UNIQUE("key")
)
